language: r
warnings_are_errors: true
sudo: required
apt_packages:
- libhdf5-serial-dev
- libgdal-dev
- libproj-dev
r_github_packages:
- jimhester/covr
after_success:
- Rscript -e 'library(covr); coveralls()'
