language: r
sudo: required
dist: trusty
cache:
  - packages
  - ccache
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libudunits2-dev
r:
  - release
  - devel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'

