language: r
warnings_are_errors: true

r_binary_packages:
  - rgdal
  - rmarkdown

notifications:
  email:
    on_success: change
    on_failure: change
#addons:
#  apt:
#    packages:
#      - libgdal-dev
#      - libproj-dev
#sudo: required
#apt_packages:
#- libhdf5-7
#- libhdf5-dev
#- libhdf5-serial-dev
#- libgdal-dev
#- libproj-dev
#r_github_packages:
#- jimhester/covr
#after_success:
#- Rscript -e 'library(covr); coveralls()'
