language: r
warnings_are_errors: true
env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

r_binary_packages:
  - rgdal

r_github_packages:
- jimhester/covr

after_success:
- Rscript -e 'library(covr); coveralls()'
