language: r
warnings_are_errors: true
env:
  global:
    - NOT_CRAN=true
before_install: 
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libhdf5-dev libhdf5-serial-dev gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev
r_binary_packages:
  - rgdal

r_github_packages:
- jimhester/covr

after_success:
- Rscript -e 'library(covr); coveralls()'
