language: r
warnings_are_errors: true
cache: packages
apt_packages:
- libgdal-dev
- libproj-dev
r_binary_packages:
- rgdal
r_github_packages:
- jimhester/covr
after_success:
- Rscript -e 'library(covr); coveralls()'
