language: r
warnings_are_errors: true
cache: packages

r_binary_packages:
  - rgdal
  - rmarkdown

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libgdal1-dev
      - netcdf-bin
      - libproj-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'
